[package]
name = "myfetch"
version = "1.2.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
sysinfo = "0.35.2"
whoami = "1.6.0"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = "symbols"
panic = "abort"
